version: '2'

services:
  ollama:
    build:
      context: .                    # Directory containing Dockerfile.ollama
      dockerfile: Dockerfile.ollama # Name of the Dockerfile
    image: ollama-with-llama3:latest # Name the built image
    volumes:
      - ollama_data:/root/.ollama    # Persistence for flexibility
    ports:
      - "11434:11434"
    restart: unless-stopped

  spamdetector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8000"
    volumes:
      - ./:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL_NAME=llama3
    restart: unless-stopped
    depends_on:
      - ollama

volumes:
  ollama_data: