version: '2'

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama  # Named volume for persistence
    ports:
      - "11434:11434"
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull llama3 && wait"]
    # Ensures the model is pulled on startup if not already present

  spamdetector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8000"
    volumes:
      - ./:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL_NAME=llama3
    restart: unless-stopped
    depends_on:
      - ollama
    # Adding a healthcheck to ensure Ollama is ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

# Define named volume
volumes:
  ollama_data: