version: '2'

services:
  spamdetector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8000"
    volumes:
      - ./:/app
    restart: unless-stopped
    env_file:
      - .env