version: '2'

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    command: serve

  spamdetector:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8040:8000"
    volumes:
      - ./:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - MODEL_NAME=llama3
    restart: unless-stopped
    depends_on:
      - ollama